"""Delete PinpointLocation table

Revision ID: 1fa746477faa
Revises: 9ab05df71cf8
Create Date: 2020-08-24 19:07:09.080280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa746477faa'
down_revision = '9ab05df71cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_pinpoint_location_name',
        table_name='pinpoint_location'
    )
    op.drop_table('pinpoint_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pinpoint_location',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=64), nullable=True),
        sa.Column('city_id', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_pinpoint_location_name',
        'pinpoint_location',
        ['name'],
        unique=False
    )
    # ### end Alembic commands ###
