"""Update railway table associations

Revision ID: 5c5459333ab9
Revises: c27d4ebd443d
Create Date: 2020-05-30 13:37:00.219783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5459333ab9'
down_revision = 'c27d4ebd443d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status_page_url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_line_name'), 'railway_line', ['name'], unique=False)
    op.create_index(op.f('ix_railway_line_status_page_url'), 'railway_line', ['status_page_url'], unique=False)
    op.create_table('railway_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['railway_category.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['railway_company.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['railway_line.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['railway_region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'region_id', 'company_id', 'line_id')
    )
    op.drop_index('ix_railway_name', table_name='railway')
    op.drop_index('ix_railway_status_page_url', table_name='railway')
    op.drop_table('railway')
    op.drop_table('railway_category_company')
    op.drop_table('railway_company_region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_company_region',
    sa.Column('railway_company_id', sa.INTEGER(), nullable=True),
    sa.Column('railway_region_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['railway_company_id'], ['railway_company.id'], ),
    sa.ForeignKeyConstraint(['railway_region_id'], ['railway_region.id'], )
    )
    op.create_table('railway_category_company',
    sa.Column('railway_category_id', sa.INTEGER(), nullable=True),
    sa.Column('railway_company_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['railway_category_id'], ['railway_category.id'], ),
    sa.ForeignKeyConstraint(['railway_company_id'], ['railway_company.id'], )
    )
    op.create_table('railway',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status_page_url', sa.VARCHAR(length=64), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['railway_category.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['railway_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_railway_status_page_url', 'railway', ['status_page_url'], unique=False)
    op.create_index('ix_railway_name', 'railway', ['name'], unique=False)
    op.drop_table('railway_info')
    op.drop_index(op.f('ix_railway_line_status_page_url'), table_name='railway_line')
    op.drop_index(op.f('ix_railway_line_name'), table_name='railway_line')
    op.drop_table('railway_line')
    # ### end Alembic commands ###
