"""Add app setting table

Revision ID: 5e6c3c0a1831
Revises: e9dddc78f1a9
Create Date: 2020-03-27 02:40:54.275994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6c3c0a1831'
down_revision = 'e9dddc78f1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=32), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_app'), 'setting', ['app'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_app'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
